[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q --cov=src/core --cov=src/database --cov-report=term-missing --cov-report=html:tests/report/html --cov-report=xml:tests/report/coverage.xml